version: '3.1'

services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - net-noharm
      
  backend-noharm:
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - net-noharm

  frontend-noharm:
    build: ./frontend
    ports:
      - 80:8080
    networks:
      - net-noharm


networks:
  net-noharm:
    driver: bridge