version: '3.1'

services:
  db:
    build: ./database
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - net-noharm
      
  backend-noharm:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    networks:
      - net-noharm

  frontend-noharm:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    networks:
      - net-noharm


networks:
  net-noharm:
    driver: bridge